### ISSUE TITLE
yo

### ISSUE THREAD

**Issue by Memexurer** [schizolab/ffmpeg-cluster#1]
lil bro you forgot the code 😭 😭 😭 😭 😭 😭 😭 i will TWIST your nutsack if i ever catch you making non-functional botnets again...

**Comment by schizolab** [comment]
bruhh I am coding it
imma sleep now
I'll see if I can finish it tomorrow

**Comment by schizolab** [comment]
>not planned


brother @Memexurer , look into the `dev` and `staging` branch

**Comment by schizolab** [comment]
it is complete, running pretty good
@Memexurer it's merged into main rn
