### ISSUE TITLE
Why VP9?

### ISSUE THREAD

**Issue by DNS** [schizolab/ffmpeg-cluster#2]
Use AV1 rather than VP9.

**Comment by schizolab** [comment]
I figured the goal was to transcode the videos for Terry Search Engine, so people can use it as soon as possible

- [ ] I was planning to use net cafe computer graphics cards to encode about 2000 videos in 1 day. AV1 nvenc was rumored to be 1/3 the speed of VP9 nvenc, so 3 times net cafe cost
- [ ] I could use the snail computer in my room to slowly transcode them to AV1 one by one and update the S3 objects in a span of... 3 months...

**Comment by schizolab** [comment]
ffmpeg vp9 can't encode long videos, always error 255 mid way
switching to AV1 419089b336cf0328ac47c8657e1ec930826dad43
you know what, av1 isn't so slow to encode actually, I saw a video saying AV1 was too slow to encode and assumed it's 10x harder from the opening of his mouth in the thumbnail...

**Comment by schizolab** [comment]
Now it seems to be working alright c1b59b466dc41fd93829b731ea6063d5f791fe25 encoding with a few laptops, will move unto net cafe next
